name: CIFuzz
on: [push, pull_request]
permissions: {}
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Note: MSan requires all libraries to be built from source, see:
        # https://github.com/google/oss-fuzz/issues/6294
        sanitizer: [address, undefined, thread]
    steps:
    - name: Fix TSan on CIFuzz
      if: matrix.sanitizer == 'thread'
      run: echo "CIFUZZ_TEST=1" >> $GITHUB_ENV
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'libvips'
        sanitizer: ${{ matrix.sanitizer }}
        bad-build-check: ${{ matrix.sanitizer != 'thread' }}
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'libvips'
        fuzz-seconds: 600
        sanitizer: ${{ matrix.sanitizer }}
    - name: Upload Crash
      uses: actions/upload-artifact@v4
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
